# Generated by Django 5.0.4 on 2024-06-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0002_usuario_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='num_calificaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
    ]
