# Generated by Django 5.0.4 on 2024-06-15 01:12

import administracion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('promocion', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=administracion.models.user_directory_path)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='administracion.promocion')),
            ],
        ),
    ]
