# Generated by Django 5.0.4 on 2024-06-06 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueques', '0002_venta_trueque_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trueque',
            name='venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='trueque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trueques.trueque'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.IntegerField(),
        ),
    ]
